name: T07 - Matrix OS

on:
  push:
    branches: [ main ]

jobs:
  echo-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Show runner OS
        run: echo "Running on ${{ matrix.os }}"
