name: T14 - Artifact upload

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create report
        run: |
          echo "Report generated at $(date -u)" > report.txt
          echo "Repository: $GITHUB_REPOSITORY" >> report.txt
          echo "Ref:        $GITHUB_REF" >> report.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-report
          path: report.txt
