name: T18 - Reusable worker

on:
  workflow_call:
    inputs:
      message:
        description: 'Message to print'
        required: true
        type: string

jobs:
  say:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: |
          echo "Reusable says: ${{ inputs.message }}"
