name: T23 - Cache demo

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  cache-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create deps file (dummy)
        run: |
          mkdir -p tools
          echo "tool-A v1.0" > tools/deps.txt

      - name: Restore cache
        id: cache
        uses: actions/cache@v4
        with:
          path: tools        # välimuistitettava kansio
          key: deps-${{ hashFiles('tools/deps.txt') }}

      - name: Show whether we hit cache
        run: |
          echo "Cache hit? -> ${{ steps.cache.outputs.cache-hit }}"
          ls -la tools
